all:
	cd kicad-footprints;git pull;../update_file fp-lib-table ~/.config/kicad/fp-lib-table
	cd kicad-symbols;git pull;../update_file sym-lib-table ~/.config/kicad/sym-lib-table
	cd kicad-packages3D;git pull
	cd kicad-templates;git pull


