#!/usr/bin/env python
import sys
import os 
import shutil

# Take two file names as input.  This program will
# read both of the input files and creating a superset of the two
# files, the program will the write this information to the second file
#  The program will ignore spaces or differences in position of
# lines in the files.  

# Usage: ./update_file f1 f2  
# The superset of the lines in f1 and f2 are written to f2. 

if len(sys.argv)!=3:
    print "Error: 2 file names expected, %d file names received",str(sys.argv)
    sys.exit(1)
else:
    superset = []    
    try:
        input1 = open(sys.argv[1],"r")
        for line in input1:
            line = line.rstrip()
            line+="\n"
            try:
                superset.index(line)
            except ValueError:
                superset.append(line)
        input1.close()
    except IOError:
        print "Error: %s does not exist"%(sys.argv[1])
        sys.exit(1)
    try:
        inout2 = open(sys.argv[2],"r")
        for line in inout2:
            line = line.rstrip()
            line+="\n"
            try:
                superset.index(line)
            except ValueError:
                superset.append(line)
        inout2.close()
    except IOError:
       pass
    inout2 = open(sys.argv[2],"w")
    for line in superset:
        inout2.write(line)

    

    
